In [8]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [9]:
iris = load_iris()

In [10]:
X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=12)

In [19]:
print(X_test)

[[5.  3.5 1.3 0.3]
 [6.3 2.5 5.  1.9]
 [4.4 3.  1.3 0.2]
 [5.7 2.8 4.1 1.3]
 [6.8 3.2 5.9 2.3]
 [6.5 3.  5.5 1.8]
 [6.2 3.4 5.4 2.3]
 [5.1 3.4 1.5 0.2]
 [7.7 3.  6.1 2.3]
 [5.1 3.3 1.7 0.5]
 [5.6 3.  4.5 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.4 1.5 0.4]
 [5.1 3.7 1.5 0.4]
 [7.  3.2 4.7 1.4]
 [7.2 3.2 6.  1.8]
 [6.7 2.5 5.8 1.8]
 [5.9 3.  4.2 1.5]
 [4.6 3.4 1.4 0.3]
 [6.3 2.5 4.9 1.5]
 [4.9 3.  1.4 0.2]
 [6.1 2.8 4.  1.3]
 [6.2 2.8 4.8 1.8]
 [6.  2.9 4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [6.7 3.  5.2 2.3]
 [6.7 3.  5.  1.7]
 [5.5 2.6 4.4 1.2]
 [4.8 3.4 1.6 0.2]
 [4.5 2.3 1.3 0.3]
 [5.1 3.5 1.4 0.3]
 [5.5 2.4 3.7 1. ]
 [6.3 2.9 5.6 1.8]
 [5.5 4.2 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [5.7 4.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [5.5 2.4 3.8 1.1]]


In [20]:
print(y_test)

[0 2 0 1 2 2 2 0 2 0 1 0 0 0 1 2 2 1 0 1 0 1 2 1 0 2 1 1 0 0 0 1 2 0 2 0 1
 1]


In [15]:
print(type(X_test))

<class 'numpy.ndarray'>


In [16]:
sample_arr = [5.8, 4.0, 1.2, 0.2]

sample_arr = np.array(sample_arr)

In [17]:
print(sample_arr)

[5.8 4.  1.2 0.2]


In [18]:
print(type(sample_arr))

<class 'numpy.ndarray'>
